# Generated by Django 2.0.7 on 2019-01-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Caategory',
        ),
    ]
