# Generated by Django 2.0.7 on 2019-01-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190115_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caategory',
            new_name='Category',
        ),
    ]
